### ISSUE TITLE
카테고리 기능 만들기

### ISSUE THREAD

**Issue by yyysolhhh** [OZ-Coding-School/oz_01_collabo-005#37]
### Describe  
카테고리 기능

### Todo
- [ ] 카테고리 전체 보기
- [ ] 카테고리 상세 보기 - 클럽 목록 연결
- [ ] 등록은 admin 페이지에서
