### ISSUE TITLE
backend django project setting

### ISSUE THREAD

**Issue by yyysolhhh** [OZ-Coding-School/oz_01_collabo-005#9]
### Describe  
장고 프로젝트 시작

### Todo
- [x] 가상환경, 장고 설치
- [x] 장고 프로젝트 세팅
- [x] 필요한 패키지 설치
